name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: intl, mbstring, xml
          tools: wp
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer install --no-interaction --no-suggest --prefer-dist
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          php vendor/bin/phpunit Tests/
